version: "3"

services:
  develop:
    image: node
    command: ["tail", "-f", "/dev/null"]
    environment:
      - HOME=/usr/src/app/cache/develop/home
    ports:
      - "49152"
      - "49153:49153"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
