version: "3"

services:
  cpp:
    build:
      context: .
      dockerfile: cpp.dockerfile
    working_dir: /usr/src/app
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
